/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
using System;

namespace ProjectEuler
{
  class Problem2
  {
    public const int LIMIT = 4000000;
    static void Main(string[] args)
    {
      Console.WriteLine("The Euler Project");
      Console.WriteLine("Problem 2\n");

      int a = 1;
      int b = 1;
      int tmp;
      int sum = 0;
      // Console.WriteLine("{0}", a);
      for (int i = 0; sum < LIMIT; i++) {
        Console.WriteLine("{0}", b);
        if (b % 2 == 0) {
          sum += b;
        }
        tmp = b;
        b += a;
        a = tmp;
      }
      Console.WriteLine("The sum of even terms of the fibonacci sequence not exceeding {0} is equal to {1}", LIMIT, sum);
    }
  }
}
